### ISSUE TITLE
A few Problems with the PHP Client.

### ISSUE THREAD

**Issue by miwi-fbsd** [aerospike/aerospike-client-php#12] opened 2015-01-12 14:32 UTC
Good Afternoon,

Since a while we are seeing in AMC problems under Reads Total/Succesful;
the difference in our live system is about 6000+ differences in Total/Succesful.

Today I have started debugging the whole thing with our developers and we found that
we can repeduce the problem with the example scripts [1].

Thus I have enabled the debug on the Aeroserver itself and there are a lot of REC NOT FOUND:4 [3] in the log. Looking
at [4] the Lines 5324 - 5326, it seems like a key or a digest is in used.

I am a bit lost here because we don't see where the problem is in our script. I came to the idea
to hack (very hackish -.-) with a bash script [5] and run the examples/basic_examples/rec-operations.php
in multiple instances to see the output.

I was suprised to see the same behaviour as in [1] and [2].

[6] Shows you a bit from the rec-operation output.The first part(Reads) of [1] will only show up when 
"Aerospike::POLICY_EXISTS_UPDATE" and "The record at PK=1 has been altered and has a newer generation" fail.
For me it looks like the bug is not from our script. I do think that the bug is in the PHP-Client though.
Do you have any idea of anything else that I can try to solve this problem?

Another problem; or more like a request, I would like to ask you to show the runtime configuration of php [7] properly.
It would also be great if it shows the current used version, that will make the devs happy :)

System Info Test ENV (Screenshots and logs are all from our Test ENV): 
1x LB
4X webserver
2x Aerospike Cluster

Ubuntu:		14.10
Aero Version:	Aerospike 3.4.0 Enterprise
Aero PHP Client: 3.3.5
PHP:		PHP 5.5.12-2ubuntu4.1 (cli) (built: Oct 29 2014 11:59:49)

[1] https://www.evernote.com/shard/s205/sh/b2bc2977-e91f-4ed4-99ea-3b45562c329c/6a550d5a984e1884ab3a19e017c617c1
[2] https://www.evernote.com/shard/s205/sh/b2bc2977-e91f-4ed4-99ea-3b45562c329c/6a550d5a984e1884ab3a19e017c617c1
[3] http://dpaste.com/0VQDC5H
[4] https://github.com/aerospike/aerospike-server/blob/master/as/src/base/thr_rw.c
[5] http://dpaste.com/1EB922D
[6] http://dpaste.com/1YD4952
[7] https://github.com/aerospike/aerospike-client-php/blob/master/doc/aerospike_config.md

Thanks, Martin.

**Comment by rbotzer** [comment] 2015-01-12 17:52
Hi Martin,

To be clear, you were seeing a problem with reads not finding their record in your code that is deployed on a web-server cluster against a 2 node Aerospike server cluster. Your setup is PHP 5.5.12 on Ubuntu 14.04 (I believe), but I don't know which web-server you're using, other than it's set up to use FPM. Can you give me those details?

From a first glance at your bash script, the use of the '-c' flag may be the problem. It triggers a cleanup of the test data. Since you're running several in parallel with this mode, those scripts will be both inserting and removing the record at the specified primary key. The 'record not found' block at the beginning of the script is there to show an example of what happens when a get() looks for a non-existent record, so nothing unexpected is happening.

I will modify the bash script and take out the '-c', and see how it behaves.

**Comment by rbotzer** [comment] 2015-01-12 20:43
I tried to reproduce the problem, and can't quite trigger it yet on my end. I need your help to locate the problem.

1. It would help if I had the type and version of your webserver, and the type and version of OS you're using. If it's Apache, are you using the prefork MPM, or [mod_proxy_fcgi + FPM](https://wiki.apache.org/httpd/PHP-FPM) (preferred mode for Apache >= 2.4)?
2. In your php.ini are you using shared memory by declaring `aerospike.shm.use=true`. That's the more efficient configuration for the webserver context?
3. Can you verify that the cluster nodes are aware of each other? For example, on my machine I'm running two nodes at ports 3000 and 3010: `$ asinfo -h192.168.119.3 -p3000 -v services && asinfo -h192.168.119.3 -p3010 -v services`. I expect yours to see each other.
4. A (different) code sample I can use to reproduce the problem. Are you using options to modify the default read-write behavior?

As I described before, what seems to be happening in the shell script you provided is that as one rec-operations script is executing another removes the record it had just set up/verified, as they all use the same key. This example is supposed to run in a single process. In normal database use case you have writes (insert, then updates) and reads on a specific records without it being deleted between those operations.

Either way, thank you for using the PHP client, and for the useful feedback you've given us in the issues you've opened. I appreciate the time you've put into it, and we prioritize fixing such bugs.

PS: Aerospike always uses digest to identify the record. The inputs to that digest, the tuple (ns, set, key) may be stored along with the record if you set OPT_POLICY_KEY to POLICY_KEY_SEND. This is mostly useful in the case of scan or query if you want to identify the records you're getting back in a human-readable way. The database itself indexes and retrieves records on their digest.

**Comment by miwi-fbsd** [comment] 2015-01-13 03:20
Hi,

Thanks for your prompt reply, I will answer all your questions a little bit later. I forgot to mention that you have to run the script twice at the same time via screen; e.g. screen win1 ./run.sh » run.log, win2 ./run.sh » run1.log. After a while (about 10/15 mins) you will see in amc the different readings, as well in the log.

A1) Using Ubuntus default nginx + php-fpm
A2) I did copy the orignal config as for now aerospike.shm.use is false. (in my test case above the webserver is not even called)
A3) Yes there are http://www.evernote.com/shard/s205/sh/1c6562da-d564-43f0-9da3-0d114067812a/46c5c0ca91ff0613c1af7e063c871b72
A4) I'll come back to you on that quickly.

**Comment by rbotzer** [comment] 2015-01-13 06:18
Great. I committed a concurrent read-write performance test that you can try in [examples/performance](https://github.com/aerospike/aerospike-client-php/tree/master/examples/performance).

Let me know if running it produces any missed writes or reads.

**Comment by miwi-fbsd** [comment] 2015-01-13 08:29
Hi,
Thanks!! Just a quick test, 

./rw-concurrent.sh -h 192.168.0.6 -p 3000 -c 4 -n 50000 -w 10
Usage: rw-concurrent.sh [-c WORKERS] [-h HOST] [-p PORT] [-n TRANSACTIONS] [-w WRITE-EVERY-N] LOG_PATH
   -h HOST     the IP address of the server. default: 127.0.0.1
   -p PORT     the port of the server. default: 3000
   -c WORKERS  the number of concurrent workers. default: 4
   -n NUM      the number of transactions per-worker. default: 50000

there is a small mistake in the docu as well, 

./rw-concurrent -h 192.168.119.3 -c 4 -n 50000 -w 10
should be ./rw-concurrent.sh :)

**Comment by rbotzer** [comment] 2015-01-13 10:52
What I get for late night commits :) . Thanks for pointing that out! I made a slight modification to the concurrent read-write script and a couple of fixes in read.php and write.php. Please check those out again.

**Comment by rbotzer** [comment] 2015-01-15 18:21
Hi Martin. I wanted to know if you've had the opportunity to try the fixed performance script. We've had what sounds like a similar bug reported this morning, so I wanted to make sure you knew it's a priority for us to identify the cause and fix it.

Again, thanks for the help in tracking down the problem.

**Closed** 2015-01-18 01:30 UTC
Labels: invalid
