### ISSUE TITLE
CHANGELOG

### ISSUE THREAD

**Issue by sergeyklay** [aerospike/aerospike-client-php#73] opened 2015-12-25 20:42 UTC
Can you please provide the changelog in each release?

+ What is deprecated
+ What is fixed
+ What is introduced
+ What is removed
+ etc...

thanks

**Comment by rbotzer** [comment] 2015-12-25 22:04
You mean a formal Changelog file? It would just be a duplicate of the [Releases](https://github.com/aerospike/aerospike-client-php/releases) section in the repo.

**Comment by sergeyklay** [comment] 2015-12-25 23:05
Yah. I mean something like that https://github.com/phalcon/cphalcon/blob/master/CHANGELOG.md
But current release information not correspond to the actual changes. Actually more changes than in the release information

**Comment by rbotzer** [comment] 2015-12-25 23:09
Yep, I'm committing that now. Thanks for the suggestion. :+1:

**Closed by rbotzer** 2015-12-25 23:09 UTC
